### ISSUE TITLE
No module named 'backend.internvl-chat-v1-5'

### ISSUE THREAD

**Issue by fatihmtlm** [matatonic/openedai-vision#13]
I've checked the backend folder, pulled  the newest version and installed the requirements again but couldn't solve this issue. 
What could be the problem? I was working very well before.

Here is the error;
```
python vision.py --model OpenGVLab/InternVL2-4B
2024-08-07 17:46:36.596 | INFO     | __main__:<module>:143 - Loading VisionQnA[internvl-chat-v1-5] with OpenGVLab/InternVL2-4B
USER_AGENT environment variable not set, consider setting it to identify your requests.
Traceback (most recent call last):
  File "C:\Users\fatih\Desktop\Vision\openedai-vision\vision.py", line 144, in <module>
    backend = importlib.import_module(f'backend.{args.backend}')
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'backend.internvl-chat-v1-5'
```

**Comment by matatonic** [comment]
That's a new one, can you share your vision.env and folder listing (with dates & size)? Please also share your python version and the output of `pip freeze`, thanks.

**Comment by matatonic** [comment]
Also, if you are able to switch, the docker image is tested and preferred.

**Comment by fatihmtlm** [comment]
I installed without docker, so I assume I don't have vision.env  . I also deleted the project folder and cloned it again today, every folder is new.  Since I installed directly, `pip freeze` displays all the packages and it is a mess. I can try installing them via `pipenv` tho.
Btw, the github link for the flash attention is broken, release version and file version doesn't match. I also installed deepspeed via prebuild custom wheel but I assumed it will be fine ?

I appologies if I've messed up the project by not using docker. It was working very well before :( I was using it since the day internvl2 announced by setting the backend manually.

**Comment by matatonic** [comment]
installing deepspeed may have broken it, it's a very complex mess of pip dependencies to keep this all working together. I wasn't able to get it all working with deepspeed installed so removed it. The pip freeze output would be helpful for me, you can attach it as a file if possible and I can compare with a working setup.

If you can't run the docker, the dedicated environment is strongly preferred. It's very hard to match the dependencies for all the models and backends.

> flash attention is broken,

Thank you! I don't have a windows setup to test with.

**Comment by fatihmtlm** [comment]
If deepspeed is problematic, I think I need to try to install Cuda and build it myself. I thought Docker is heavy, but now I am in dependency hell. I will definitely try a dedicated env and Docker if dedicated env don't work. Again, I am sorry if this is an issue with my dependencies. Also, I will only be able to test these after the weekend, unfortunately. 

Here is the pip freeze result in case you still want to check: 
[pip_freeze.txt](https://github.com/user-attachments/files/16549344/pip_freeze.txt)

**Comment by fatihmtlm** [comment]
Sorry, the issue was on my side. I created a venv with pipenv and the error is gone. I think It wasnt about deepspeed, nor torch (I am using symboling links for torch to use the system version of it since I don't have much space to install it twice).

Thank you for your time. I am sorry for bothering you.

**Comment by matatonic** [comment]
No problem, that's great! Glad it's working for you.
