### ISSUE TITLE
inference for certain images work while other images fail with a 500 error from the PIL library

### ISSUE THREAD

**Issue by saket424** [matatonic/openedai-vision#3]
Issue is documented here with error logs

https://github.com/allanbunch/node-red-openai-api/issues/24

**Comment by matatonic** [comment]
Thank you, I'm currently travelling with limited internet access but will look at this as soon as I can.

**Comment by matatonic** [comment]
At a quick glance there doesn't seem to be anything unusual about the image, I'll need to test further when I have more access.
This test was fine:
```
curl https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/ChrisLitherlandBourbonSt.jpg/1200px-ChrisLitherlandBourbonSt.jpg -sO
```
```python
>>> Image.open(io.BytesIO(open('1200px-ChrisLitherlandBourbonSt.jpg', 'rb').read()))
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1200x798 at 0x7F9C8625BD30>
```

**Comment by matatonic** [comment]
Can you include the output if pip freeze? If you're using a specific docker image version of openedai-vision please include which one.

**Comment by saket424** [comment]
@matatonic , thanks for this wonderful project and such a speedy response. I saw the problem even with the newest v0.26.0 version of openedai-vision. I am going to close this issue for the present as it appears things work better when the nodered and openedai-vision docker containers are co-located on the same machine. It sure is a weird issue and i will report back if i get any further insights.

**Comment by matatonic** [comment]
Do you think this could be some kind of race condition with loading the image slowly over the net? It's my only guess right now.
